.PHONY: clean All

All:
	@echo "----------Building project:[ Julia - Release ]----------"
	@$(MAKE) -f  "Julia.mk"
clean:
	@echo "----------Cleaning project:[ Julia - Release ]----------"
	@$(MAKE) -f  "Julia.mk" clean
