.PHONY: clean All

All:
	@echo "----------Building project:[ Buffer2OpenGL - Release ]----------"
	@$(MAKE) -f  "Buffer2OpenGL.mk"
clean:
	@echo "----------Cleaning project:[ Buffer2OpenGL - Release ]----------"
	@$(MAKE) -f  "Buffer2OpenGL.mk" clean
